# Build settings
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Peiyu and Anna's Final Project]
description: [This project allows users to get the rating for the movie, 
the sentiment analysis results on the movie reviews, 
the similarity result on the first and second reviews,
and the most common words used in the reviews on IMDB,
when entering an IMDB ID for a movie.]

Sample result: [For the movie Bullet train (Movie ID: 12593682)
A sample result would look like this:
Recommend!
The rating is 7.3.
The sentiment analysis results are {'neg': 0.042, 'neu': 0.761, 'pos': 0.198, 'compound': 0.9994}.
The similarity result are 54.
The most common words are

movie: 7
just: 6
action: 6
train: 5
like: 5
great: 5
fun: 5
get: 4
brad: 4
bit: 4
tried: 3
taylor-johnson: 3
seeing: 3
one: 3
japanese: 3
first: 3
cast: 3
also: 3
aaron: 3
wick: 2
watch: 2
understand: 2
ultrascreen: 2
tyree: 2
time: 2
think: 2
things: 2
taken: 2]